name: Update README with Repositories

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README
        uses: ramnes/github-repository-activity-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: .github/recent_repos.md
          repo: AbdollahRasti/cryptocurrency-price-tracker

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/recent_repos.md
          git commit -m 'Update recent repositories'
          git push
